/* Generated by tools/test_hash_parity.py — do not edit. */
#pragma once
#include <stdint.h>

static const struct { const char *domain; uint32_t hash; } kHashVectors[] = {
    { "doubleclick.net", 0x6a55470du },
    { "ads.example.co.uk", 0xdb7fd9c3u },
    { "", 0x811c9dc5u },
    { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 0x0bd05be7u },
    { "cdn-3.ad-server-01.example.com", 0x16f806ecu },
    { "xn--80ak6aa92e.com", 0x540ad02cu },
};
