#!/usr/bin/env python3
"""Assert the Python hash and main/fnv1a.h agree, and emit main/hash_vectors.h.

Compiles the real firmware header (not a copy of it) with the host cc, so this
fails if either implementation drifts. Run it before every blocklist build.
"""
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "..", "main", "fnv1a.h")
OUT_HEADER = os.path.join(HERE, "..", "main", "hash_vectors.h")

sys.path.insert(0, HERE)
from build_blocklist import fnv1a  # noqa: E402

LONG_253 = ".".join(["a" * 63] * 3) + "." + "a" * 61   # exactly 253 chars

VECTORS = [
    "doubleclick.net",
    "ads.example.co.uk",
    "",
    LONG_253,
    "cdn-3.ad-server-01.example.com",
    "xn--80ak6aa92e.com",
]

C_HARNESS = r'''
#include <stdio.h>
#include <string.h>
#include "fnv1a.h"
int main(int argc, char **argv) {
    for (int i = 1; i < argc; i++)
        printf("%08x\n", fnv1a(argv[i], strlen(argv[i])));
    return 0;
}
'''


def c_hashes(vectors):
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "h.c")
        exe = os.path.join(td, "h")
        with open(src, "w") as f:
            f.write(C_HARNESS)
        subprocess.run(["cc", "-O1", "-I", os.path.dirname(HEADER), src, "-o", exe],
                       check=True)
        out = subprocess.run([exe] + vectors, check=True, capture_output=True, text=True)
    return [int(x, 16) for x in out.stdout.split()]


def main() -> int:
    assert len(LONG_253) == 253, len(LONG_253)

    py = [fnv1a(v) for v in VECTORS]
    assert py[0] != py[1], "sanity: distinct inputs hashed the same"
    assert fnv1a("") == 2166136261, "empty string must be the FNV offset basis"

    try:
        c = c_hashes(VECTORS)
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        print(f"SKIP: no working host cc ({e}) — Python-only checks passed")
        c = None

    if c is not None:
        for v, p, cc in zip(VECTORS, py, c):
            assert p == cc, f"MISMATCH {v!r}: python {p:#010x} != c {cc:#010x}"
        print(f"parity ok: {len(VECTORS)} vectors match between Python and fnv1a.h")

    with open(OUT_HEADER, "w") as f:
        f.write("/* Generated by tools/test_hash_parity.py — do not edit. */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("static const struct { const char *domain; uint32_t hash; } "
                "kHashVectors[] = {\n")
        for v, h in zip(VECTORS, py):
            f.write(f'    {{ "{v}", {h:#010x}u }},\n')
        f.write("};\n")
    print(f"wrote {os.path.normpath(OUT_HEADER)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
